Add update loop
GuillaumeDesforges/pixijs-typescript-starter pull request #9
Opened 2021-04-16 13:44 UTC by pparkkin

I felt like the starter could do with an update loop. Feels like something you almost always need anyway.

2021-04-16 15:02 UTC, GuillaumeDesforges commented
Hi! Thanks for the PR 🙂 
You are right, an update loop is most needed in this starter!

That being said, I'm against promoting the use of wild global variables in _any_ code, so I wouldn't like to be written in a repo I own.
I'm being picky here, but I'd really like if we could find another pattern, so as to invite people to start on "solid foundations".

If we can't think of any better way to store the global state, we can move forward with what you've written.

2021-04-16 15:04 UTC, GuillaumeDesforges requested changes
Hi! Thanks for the PR 🙂 
You are right, an update loop is most needed in this starter!

That being said, I'm against promoting the use of wild global variables in _any_ code, so I wouldn't like to be written in a repo I own.
I'm being picky here, but I'd really like if we could find another pattern, so as to invite people to start on "solid foundations".

If we can't think of any better way to store the global state, we can move forward with what you've written.

2021-04-16 15:04 UTC, GuillaumeDesforges commented on src/index.ts
> +var xv = 1;
Wild global variables

2021-04-16 17:15 UTC, pparkkin commented
You're right about the global variables of course. I pushed a commit that I hope fixes it.

2021-04-19 12:57 UTC, GuillaumeDesforges approved these changes

2021-04-19 12:57 UTC, GuillaumeDesforges commented
Awesome job, thank you very much for your contribution!

2021-04-19 12:57 UTC, merged